### ISSUE TITLE
IL2CPU Error "System.Exception: Native code encountered, plug required. Check build output for more information."

### ISSUE THREAD

**Issue by qveezzx** [LumaTechnologies/SphereOS#16]
![image](https://github.com/LumaTechnologies/SphereOS/assets/120045358/72713d3e-0e8b-40c9-b791-5a980390466f)

**Comment by 9xbt** [comment]
That happens because Cosmos moved plugs to a separage nuget package, so add the Cosmos.Plugs nuget package, save, and it should work now

**Comment by Jspa2** [comment]
Resolved 6d0b1f454b5e05375cc6be9136347fb2dfbe3100
